name = "StylizedAltruism"
uuid = "3994d275-1c22-4dfe-948c-9034d80195bf"
authors = ["Eirik Eylands Brandsaas"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
julia = "1"
Interpolations = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
